# Generated by Django 2.2.1 on 2019-05-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('surrogate_id', models.IntegerField(db_column='SPREMRG_SURROGATE_ID', primary_key=True, serialize=False)),
                ('pidm', models.IntegerField(db_column='SPREMRG_PIDM')),
                ('priority', models.CharField(db_column='SPREMRG_PRIORITY', max_length=4)),
                ('relt_code', models.CharField(db_column='SPREMRG_RELT_CODE', max_length=4, null=True)),
                ('last_name', models.CharField(db_column='SPREMRG_LAST_NAME', max_length=240)),
                ('first_name', models.CharField(db_column='SPREMRG_FIRST_NAME', max_length=240)),
                ('mi', models.CharField(db_column='SPREMRG_MI', max_length=240, null=True)),
                ('street_line1', models.CharField(db_column='SPREMRG_STREET_LINE1', max_length=300, null=True)),
                ('street_line2', models.CharField(db_column='SPREMRG_STREET_LINE2', max_length=300, null=True)),
                ('street_line3', models.CharField(db_column='SPREMRG_STREET_LINE3', max_length=300, null=True)),
                ('city', models.CharField(db_column='SPREMRG_CITY', max_length=200, null=True)),
                ('stat_code', models.CharField(db_column='SPREMRG_STAT_CODE', max_length=12, null=True)),
                ('natn_code', models.CharField(db_column='SPREMRG_NATN_CODE', max_length=20, null=True)),
                ('zip', models.CharField(db_column='SPREMRG_ZIP', max_length=120, null=True)),
                ('ctry_code_phone', models.CharField(db_column='SPREMRG_CTRY_CODE_PHONE', max_length=16, null=True)),
                ('phone_area', models.CharField(db_column='SPREMRG_PHONE_AREA', max_length=24, null=True)),
                ('phone_number', models.CharField(db_column='SPREMRG_PHONE_NUMBER', max_length=48, null=True)),
                ('phone_ext', models.CharField(db_column='SPREMRG_PHONE_EXT', max_length=40, null=True)),
                ('activity_date', models.DateTimeField(auto_now=True, db_column='SPREMRG_ACTIVITY_DATE')),
            ],
            options={
                'db_table': 'SPREMRG',
            },
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('pidm', models.IntegerField(db_column='ZGBNNN_PIDM', primary_key=True, serialize=False)),
                ('evacuation_assistance', models.CharField(db_column='ZGBNNN_REQ_ASSIST', max_length=4, null=True)),
                ('external_email', models.CharField(db_column='ZGBNNN_EMAIL_ADDRESS', max_length=512, null=True)),
                ('campus_email', models.CharField(db_column='ZGBNNN_EMAIL_ADDRESS2', max_length=512, null=True)),
                ('primary_phone', models.CharField(db_column='ZGBNNN_MOBILE_PHONE', max_length=72, null=True)),
                ('alternate_phone', models.CharField(db_column='ZGBNNN_BUSINESS_PHONE', max_length=72, null=True)),
                ('sms_status_ind', models.CharField(db_column='ZGBNNN_SMS_STATUS_IND', max_length=4, null=True)),
                ('sms_device', models.CharField(db_column='ZGBNNN_SMS_DEVICE_1', max_length=72, null=True)),
                ('activity_date', models.DateTimeField(auto_now=True, db_column='ZGBNNN_ACTIVITY_DATE', null=True)),
            ],
            options={
                'db_table': 'ZGBNNN',
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('pidm', models.IntegerField(db_column='ZGBIDMP_PIDM', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='ZGBIDMP_USERNAME', max_length=120, null=True)),
                ('email', models.CharField(db_column='ZGBIDMP_EMAIL', max_length=512, null=True)),
                ('first_name', models.CharField(db_column='ZGBIDMP_FIRST_NAME', max_length=240, null=True)),
                ('last_name', models.CharField(db_column='ZGBIDMP_LAST_NAME', max_length=240, null=True)),
                ('mi', models.CharField(db_column='ZGBIDMP_MI', max_length=240, null=True)),
            ],
            options={
                'db_table': 'ZGBIDMP',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('code', models.CharField(db_column='STVRELT_CODE', max_length=4, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='STVRELT_DESC', max_length=120, null=True)),
            ],
            options={
                'db_table': 'STVRELT',
            },
        ),
    ]
