# Generated by Django 2.2.1 on 2019-08-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.CharField(db_column='NATION_ID', max_length=4, primary_key=True, serialize=False)),
                ('value', models.CharField(db_column='NATION_VALUE', max_length=120, null=True)),
                ('phone_code', models.CharField(db_column='NATION_PHONE_CODE', max_length=16, null=True)),
                ('svgimg', models.CharField(db_column='NATION_SVGIMG', max_length=72, null=True)),
            ],
            options={
                'db_table': 'NATION',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.CharField(db_column='STATE_ID', max_length=4, primary_key=True, serialize=False)),
                ('value', models.CharField(db_column='STATE_VALUE', max_length=120, null=True)),
            ],
            options={
                'db_table': 'STATE',
            },
        ),
    ]
